In [1]:
import numpy as np
import pandas as pd
import pyodbc
import re

In [2]:
!pip install unidecode

Requirement already satisfied: unidecode in d:\anaconda\lib\site-packages (1.4.0)

In [3]:
import pyodbc

server = r"Varun\SQLEXPRESS"
database = "campusx_project2"

connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"Server={server};"
    f"Database={database};"
    "Trusted_Connection=yes;"
)

conn = pyodbc.connect(connection_string)

In [4]:
query = "select * from olist_customers_dataset"
customers = pd.read_sql(query,conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\1038818937.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql(query,conn)

### Olist customer dataset

In [5]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,sao paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,rio de janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,taboao da serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,osasco,SP

In [6]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [7]:
customers.sample(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
4422,0b779368ba5d4d8f91414e244c260dce,6e48a742733b07300f4bc5ef5847a0b8,89560,videira,SC
57721,94cf3e8a7892ee0fdd046c0c08c2c38c,d275b278b0894a9ffb5af58318a86b44,49097,aracaju,SE
63107,a26fe43b2f7f0f2baf12a881ced45d66,eba66367d1ba25bb9b96b35f534f8d3c,30220,belo horizonte,MG
92107,ecbbe3ed9ad0fdcc1d1e698b2554c986,fb2c5015c63a4dab28b65c5e0d9b95ec,13428,piracicaba,SP
52451,874d93028c161780cf20da0b7b3797b5,c17c49aa703f9eda6a57d5cf2543821e,26041,nova iguacu,RJ
95917,f6bb7b61f69f163fa92942a84c9233d6,623632ea052eb9b98d86fba7b8498df8,91420,porto alegre,RS
81945,d256c1df237b8ea64ecd66b77cf142df,6864d1ea40530414cf6b04c740450443,65075,sao luis,MA
39383,65d9f34a0361382394c7ede678879c0b,dc7329494bcf58a353c1fece65a73aef,30110,belo horizonte,MG
34633,59941adf97664d2158b52f86297f0659,6acbe9a0b796a069ec0dc400d74539fe,33400,lagoa santa,MG
30055,4d75283fa7a9224dafc28140b8a13f45,5bc14c2233f3cbfff394f3dc8e77041d,88501,lages,SC

In [8]:
customers["customer_city"]=customers["customer_city"].str.title()

In [9]:
customers["customer_id"].nunique()

99441

In [10]:
customers["customer_unique_id"].nunique()

96096

In [269]:
99441 - 96096

3345

In [11]:
# aise ek bhi column nahi jisme value same hai 
sum(customers["customer_id"] ==  customers["customer_unique_id"])

0

In [12]:
query = "select * from olist_geolocation_dataset"
geo = pd.read_sql(query, conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\82253223.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  geo = pd.read_sql(query, conn)

In [13]:
geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,04469,-23.692535,-46.668392,são paulo,SP
1,04405,-23.675543,-46.657204,sao paulo,SP
2,04447,-23.692816,-46.677841,sao paulo,SP
3,04470,-23.711924,-46.651859,sao paulo,SP
4,04458,-23.690666,-46.673580,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068640,-52.010704,tapejara,RS
1000159,99900,-27.877125,-52.224884,getulio vargas,RS
1000160,99950,-28.071856,-52.014717,tapejara,RS
1000161,99980,-28.388931,-51.846870,david canabarro,RS
1000162,99950,-28.070103,-52.018658,tapejara,RS

In [14]:
geo["geolocation_city"]=geo["geolocation_city"].str.title()

In [15]:
geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,04469,-23.692535,-46.668392,São Paulo,SP
1,04405,-23.675543,-46.657204,Sao Paulo,SP
2,04447,-23.692816,-46.677841,Sao Paulo,SP
3,04470,-23.711924,-46.651859,Sao Paulo,SP
4,04458,-23.690666,-46.673580,Sao Paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068640,-52.010704,Tapejara,RS
1000159,99900,-27.877125,-52.224884,Getulio Vargas,RS
1000160,99950,-28.071856,-52.014717,Tapejara,RS
1000161,99980,-28.388931,-51.846870,David Canabarro,RS
1000162,99950,-28.070103,-52.018658,Tapejara,RS

In [16]:
geo.duplicated().sum()

np.int64(262154)

In [17]:
geo.drop_duplicates(inplace = True)

In [18]:
geo.shape

(738009, 5)

In [19]:
geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,04469,-23.692535,-46.668392,São Paulo,SP
1,04405,-23.675543,-46.657204,Sao Paulo,SP
2,04447,-23.692816,-46.677841,Sao Paulo,SP
3,04470,-23.711924,-46.651859,Sao Paulo,SP
4,04458,-23.690666,-46.673580,Sao Paulo,SP
...,...,...,...,...,...
1000155,99965,-28.180655,-52.034367,Agua Santa,RS
1000156,99950,-28.072187,-52.011272,Tapejara,RS
1000157,99950,-28.068863,-52.012966,Tapejara,RS
1000158,99950,-28.068640,-52.010704,Tapejara,RS
1000161,99980,-28.388931,-51.846870,David Canabarro,RS

In [20]:
# drop lat and long kyu ki joh kaam city wala column karta hai power bi mein woh same lat and long so better lat and long uda do 
geo.drop(columns = ["geolocation_lat","geolocation_lng"],inplace = True)

In [21]:
geo

        geolocation_zip_code_prefix geolocation_city geolocation_state
0                             04469        São Paulo                SP
1                             04405        Sao Paulo                SP
2                             04447        Sao Paulo                SP
3                             04470        Sao Paulo                SP
4                             04458        Sao Paulo                SP
...                             ...              ...               ...
1000155                       99965       Agua Santa                RS
1000156                       99950         Tapejara                RS
1000157                       99950         Tapejara                RS
1000158                       99950         Tapejara                RS
1000161                       99980  David Canabarro                RS

[738009 rows x 3 columns]

In [22]:
# this city name are in portugeues nee dto convert into english 
geo["geolocation_city"].sample(10)

458876       Rio De Janeiro
437000       Rio De Janeiro
173770             Miracatu
185986     Campos Do Jordao
390746          Porto Feliz
97665             Guarulhos
664164    Jenipapo De Minas
12128             Sao Paulo
816490               Palmas
837124              Miranda
Name: geolocation_city, dtype: object

In [23]:
geo["geolocation_city"].nunique()

8011

In [24]:
from unidecode import unidecode

In [25]:
geo["geolocation_city"]=geo["geolocation_city"].apply(lambda x : unidecode(x))

In [26]:
geo["geolocation_city"].nunique()

5969

In [27]:
geo["geolocation_city"].sample(10)

340837               Sao Paulo
220459               Rio Claro
743281               Fortaleza
273051              Guararapes
546160          Belo Horizonte
68129              Carapicuiba
252246              Araraquara
341034               Sao Paulo
687802    Vitoria Da Conquista
370298               Sao Paulo
Name: geolocation_city, dtype: object

In [28]:
def contains_number(s):
    return any(i.isdigit() for i in str(s))

In [29]:
geo[geo["geolocation_city"].apply(contains_number)]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
286136,17970,Sao Joao Do Pau D%26Apos%3Balho,SP
538905,29735,Quilometro 14 Do Mutum,ES
539470,29735,Quilometro 14 Do Mutum,ES
727510,57010,Maceia3,AL
786179,71880,Riacho Fundo 2,DF
823386,78278,Lambari D%26Apos%3Boeste,MT
896733,87365,4O. Centenario,PR
896977,87365,4o Centenario,PR
897217,87365,4o Centenario,PR
977775,96130,Colonia Z-3,RS
977787,96130,Colonia Z-3,RS
977813,96130,Colonia Z-3,RS

In [30]:
import re 

def remove_numbers(s):
    return re.sub(r'\d+','',str(s))

In [31]:
geo["geolocation_city"]=geo["geolocation_city"].apply(remove_numbers)

In [32]:
geo

        geolocation_zip_code_prefix geolocation_city geolocation_state
0                             04469        Sao Paulo                SP
1                             04405        Sao Paulo                SP
2                             04447        Sao Paulo                SP
3                             04470        Sao Paulo                SP
4                             04458        Sao Paulo                SP
...                             ...              ...               ...
1000155                       99965       Agua Santa                RS
1000156                       99950         Tapejara                RS
1000157                       99950         Tapejara                RS
1000158                       99950         Tapejara                RS
1000161                       99980  David Canabarro                RS

[738009 rows x 3 columns]

In [33]:
geo[geo["geolocation_city"].apply(contains_number)]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [34]:
geo[geo["geolocation_zip_code_prefix"] == "17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
285731,17970,Sao Joao Do Pau D'Alho,SP
285753,17970,Sao Joao Do Pau D'Alho,SP
285831,17970,Sao Joao Do Pau D'Alho,SP
285863,17970,Sao Joao Do Pau D Alho,SP
285948,17970,Sao Joao Do Pau D Alho,SP
285999,17970,Sao Joao Do Pau D'Alho,SP
286008,17970,Sao Joao Do Pau D'Alho,SP
286018,17970,Sao Joao Do Pau Dalho,SP
286064,17970,Sao Joao Do Pau D'Alho,SP
286112,17970,Sao Joao Do Pau Dalho,SP
286136,17970,Sao Joao Do Pau D%Apos%Balho,SP
286232,17970,Sao Joao Do Pau D Alho,SP
286250,17970,Sao Joao Do Pau D'Alho,SP
286257,17970,Sao Joao Do Pau D'Alho,SP
286422,17970,Sao Joao Do Pau D'Alho,SP

In [35]:
geo["geolocation_city"]=geo["geolocation_city"].str.replace("'","",regex = False)

In [36]:
geo[geo["geolocation_zip_code_prefix"] == "17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
285731,17970,Sao Joao Do Pau DAlho,SP
285753,17970,Sao Joao Do Pau DAlho,SP
285831,17970,Sao Joao Do Pau DAlho,SP
285863,17970,Sao Joao Do Pau D Alho,SP
285948,17970,Sao Joao Do Pau D Alho,SP
285999,17970,Sao Joao Do Pau DAlho,SP
286008,17970,Sao Joao Do Pau DAlho,SP
286018,17970,Sao Joao Do Pau Dalho,SP
286064,17970,Sao Joao Do Pau DAlho,SP
286112,17970,Sao Joao Do Pau Dalho,SP
286136,17970,Sao Joao Do Pau D%Apos%Balho,SP
286232,17970,Sao Joao Do Pau D Alho,SP
286250,17970,Sao Joao Do Pau DAlho,SP
286257,17970,Sao Joao Do Pau DAlho,SP
286422,17970,Sao Joao Do Pau DAlho,SP

In [37]:
geo.duplicated().sum()

np.int64(718393)

In [38]:
geo[geo["geolocation_city"].str.contains("'", na = False)]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [39]:
geo[geo["geolocation_city"].str.startswith("*", na = False)]

       geolocation_zip_code_prefix geolocation_city geolocation_state
851430                       81470         * Cidade                PR

In [40]:
geo["geolocation_city"]=geo["geolocation_city"].str.replace("*","",regex = False)

In [41]:
geo[geo["geolocation_city"].str.startswith("*", na = False)]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [42]:
geo[geo["geolocation_city"].str.startswith(".", na = False)]

       geolocation_zip_code_prefix    geolocation_city geolocation_state
525385                       28930  ...Arraial Do Cabo                RJ

In [43]:
geo["geolocation_city"]=geo["geolocation_city"].str.replace(".","",regex = False)

In [44]:
geo[geo["geolocation_city"].str.startswith(".", na = False)]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [45]:
geo["geolocation_city"].nunique()

5966

In [46]:
geo["geolocation_city"].duplicated().sum()

np.int64(732043)

In [47]:
# upar ke itne cheeze karne ke wajah agar hum niche wala code run kar de toh sabhi faltu ke numbers haatt jayenge

In [48]:
def keep_only_text(x):
    if pd.isna(x):
        return x 
    # remove everything except alphabets and spaces 
    return re.sub(r"[^A-Za-z\s]","",str(x)).strip()

In [49]:
geo["geolocation_city"]=geo["geolocation_city"].apply(keep_only_text)

In [50]:
geo[geo["geolocation_zip_code_prefix"] == "17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
285731,17970,Sao Joao Do Pau DAlho,SP
285753,17970,Sao Joao Do Pau DAlho,SP
285831,17970,Sao Joao Do Pau DAlho,SP
285863,17970,Sao Joao Do Pau D Alho,SP
285948,17970,Sao Joao Do Pau D Alho,SP
285999,17970,Sao Joao Do Pau DAlho,SP
286008,17970,Sao Joao Do Pau DAlho,SP
286018,17970,Sao Joao Do Pau Dalho,SP
286064,17970,Sao Joao Do Pau DAlho,SP
286112,17970,Sao Joao Do Pau Dalho,SP
286136,17970,Sao Joao Do Pau DAposBalho,SP
286232,17970,Sao Joao Do Pau D Alho,SP
286250,17970,Sao Joao Do Pau DAlho,SP
286257,17970,Sao Joao Do Pau DAlho,SP
286422,17970,Sao Joao Do Pau DAlho,SP

In [51]:
geo["geolocation_city"]=geo["geolocation_city"].str.replace("Sao Joao Do Pau D Alho","Sao Joao Do Pau DAlho")

In [52]:
geo[geo["geolocation_zip_code_prefix"] == "17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
285731,17970,Sao Joao Do Pau DAlho,SP
285753,17970,Sao Joao Do Pau DAlho,SP
285831,17970,Sao Joao Do Pau DAlho,SP
285863,17970,Sao Joao Do Pau DAlho,SP
285948,17970,Sao Joao Do Pau DAlho,SP
285999,17970,Sao Joao Do Pau DAlho,SP
286008,17970,Sao Joao Do Pau DAlho,SP
286018,17970,Sao Joao Do Pau Dalho,SP
286064,17970,Sao Joao Do Pau DAlho,SP
286112,17970,Sao Joao Do Pau Dalho,SP
286136,17970,Sao Joao Do Pau DAposBalho,SP
286232,17970,Sao Joao Do Pau DAlho,SP
286250,17970,Sao Joao Do Pau DAlho,SP
286257,17970,Sao Joao Do Pau DAlho,SP
286422,17970,Sao Joao Do Pau DAlho,SP

In [53]:
geo.duplicated().sum()

np.int64(718397)

In [54]:
geo.drop_duplicates(inplace = True)

In [55]:
geo.duplicated().sum()

np.int64(0)

In [56]:
geo.shape

(19612, 3)

In [57]:
geo

       geolocation_zip_code_prefix      geolocation_city geolocation_state
0                            04469             Sao Paulo                SP
1                            04405             Sao Paulo                SP
2                            04447             Sao Paulo                SP
3                            04470             Sao Paulo                SP
4                            04458             Sao Paulo                SP
...                            ...                   ...               ...
999774                       99955          Vila Langaro                RS
999780                       99970               Ciriaco                RS
999786                       99910      Floriano Peixoto                RS
999803                       99920              Erebango                RS
999846                       99952  Santa Cecilia Do Sul                RS

[19612 rows x 3 columns]

In [58]:
geo["geolocation_city"].nunique()

5962

In [59]:
# performinfing same steps for customer table city column 
customers["customer_city"]=customers["customer_city"].apply(lambda x : unidecode(x))

In [60]:
customers["customer_city"]

0                 Osasco
1            Itapecerica
2           Nova Venecia
3               Mendonca
4              Sao Paulo
              ...
99436             Parobe
99437     Rio De Janeiro
99438    Taboao Da Serra
99439            Alfenas
99440             Osasco
Name: customer_city, Length: 99441, dtype: object

In [61]:
customers["customer_city"]=customers["customer_city"].apply(keep_only_text)

In [62]:
customers.duplicated().sum()

np.int64(0)

In [63]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,Osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,Itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,Nova Venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,Mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,Sao Paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,Parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,Rio De Janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,Taboao Da Serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,Alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,Osasco,SP

### Products dataset

In [64]:
query = "select * from olist_products_dataset"
products = pd.read_sql(query, conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\11933789.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql(query, conn)

In [65]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,2a5fd02982127e736ae8f4d6d020fcc8,utilidades_domesticas,33.0,1520.0,1.0,5950,35,35,29
1,3dcb77af8b9587985d046b195e105475,cama_mesa_banho,59.0,289.0,1.0,3400,36,10,35
2,cec51758e9839eb5414b214934430da6,sinalizacao_e_seguranca,50.0,853.0,1.0,450,16,11,16
3,b3f3d2afe706552a90fd99f870e4ddf5,None,NaN,NaN,NaN,3000,33,40,22
4,5afcae10f25795d55b858f6a2b95233b,brinquedos,36.0,509.0,1.0,800,40,10,40
...,...,...,...,...,...,...,...,...,...
32946,325c397d5d1eebe97422d6bc1ed8709d,moveis_escritorio,30.0,210.0,3.0,5600,90,30,40
32947,5e53af05c040b01584b81b3549945faf,construcao_ferramentas_ferramentas,53.0,470.0,3.0,200,16,16,16
32948,87b489e8ad10cd2b4e631cc1af34ff00,moveis_decoracao,55.0,287.0,2.0,700,28,50,28
32949,c8a148c82c4a80df54e7ceea266f9fb5,construcao_ferramentas_construcao,27.0,116.0,3.0,6900,45,19,45
32950,c0603988d17e4588dfce0f7f01978557,cama_mesa_banho,60.0,516.0,1.0,400,26,18,23

In [66]:
products.drop(columns = ['product_name_lenght','product_description_lenght','product_weight_g','product_length_cm','product_height_cm','product_width_cm'],inplace = True)

In [67]:
products

,product_id,product_category_name,product_photos_qty
0,2a5fd02982127e736ae8f4d6d020fcc8,utilidades_domesticas,1.0
1,3dcb77af8b9587985d046b195e105475,cama_mesa_banho,1.0
2,cec51758e9839eb5414b214934430da6,sinalizacao_e_seguranca,1.0
3,b3f3d2afe706552a90fd99f870e4ddf5,None,NaN
4,5afcae10f25795d55b858f6a2b95233b,brinquedos,1.0
...,...,...,...
32946,325c397d5d1eebe97422d6bc1ed8709d,moveis_escritorio,3.0
32947,5e53af05c040b01584b81b3549945faf,construcao_ferramentas_ferramentas,3.0
32948,87b489e8ad10cd2b4e631cc1af34ff00,moveis_decoracao,2.0
32949,c8a148c82c4a80df54e7ceea266f9fb5,construcao_ferramentas_construcao,3.0
32950,c0603988d17e4588dfce0f7f01978557,cama_mesa_banho,1.0

In [68]:
products

,product_id,product_category_name,product_photos_qty
0,2a5fd02982127e736ae8f4d6d020fcc8,utilidades_domesticas,1.0
1,3dcb77af8b9587985d046b195e105475,cama_mesa_banho,1.0
2,cec51758e9839eb5414b214934430da6,sinalizacao_e_seguranca,1.0
3,b3f3d2afe706552a90fd99f870e4ddf5,None,NaN
4,5afcae10f25795d55b858f6a2b95233b,brinquedos,1.0
...,...,...,...
32946,325c397d5d1eebe97422d6bc1ed8709d,moveis_escritorio,3.0
32947,5e53af05c040b01584b81b3549945faf,construcao_ferramentas_ferramentas,3.0
32948,87b489e8ad10cd2b4e631cc1af34ff00,moveis_decoracao,2.0
32949,c8a148c82c4a80df54e7ceea266f9fb5,construcao_ferramentas_construcao,3.0
32950,c0603988d17e4588dfce0f7f01978557,cama_mesa_banho,1.0

In [69]:
products['product_category_name'].unique()

array(['utilidades_domesticas', 'cama_mesa_banho',
       'sinalizacao_e_seguranca', None, 'brinquedos', 'eletronicos',
       'moveis_decoracao', 'relogios_presentes', 'consoles_games',
       'perfumaria', 'papelaria', 'esporte_lazer', 'eletrodomesticos',
       'instrumentos_musicais', 'construcao_ferramentas_construcao',
       'bebes', 'informatica_acessorios', 'ferramentas_jardim',
       'fashion_calcados', 'automotivo', 'moveis_sala', 'beleza_saude',
       'pet_shop', 'cool_stuff', 'fashion_bolsas_e_acessorios',
       'casa_construcao', 'pcs', 'livros_interesse_geral',
       'eletroportateis', 'moveis_escritorio', 'livros_tecnicos',
       'telefonia', 'market_place', 'telefonia_fixa', 'bebidas',
       'fashion_roupa_feminina', 'construcao_ferramentas_iluminacao',
       'malas_acessorios', 'casa_conforto', 'artigos_de_natal', 'artes',
       'alimentos_bebidas', 'industria_comercio_e_negocios',
       'portateis_casa_forno_e_cafe', 'construcao_ferramentas_seguranca',
       'audio', 'eletrodomesticos_2', 'livros_importados',
       'fashion_roupa_masculina', 'construcao_ferramentas_jardim',
       'fashion_underwear_e_moda_praia', 'climatizacao',
       'agro_industria_e_comercio', 'la_cuisine', 'alimentos',
       'artigos_de_festas', 'fashion_esporte',
       'moveis_cozinha_area_de_servico_jantar_e_jardim', 'moveis_quarto',
       'cine_foto', 'construcao_ferramentas_ferramentas',
       'fraldas_higiene', 'musica', 'dvds_blu_ray', 'flores',
       'casa_conforto_2', 'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'tablets_impressao_imagem',
       'moveis_colchao_e_estofado', 'artes_e_artesanato', 'pc_gamer',
       'fashion_roupa_infanto_juvenil', 'cds_dvds_musicais'], dtype=object)

In [70]:
query = "select * from product_category_name_translation;"
product_name = pd.read_sql(query,conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\3710577495.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  product_name = pd.read_sql(query,conn)

In [71]:
product_name

                 Product Category    product category in english
0           product_category_name  product_category_name_english
1                    beleza_saude                  health_beauty
2          informatica_acessorios          computers_accessories
3                      automotivo                           auto
4                 cama_mesa_banho                 bed_bath_table
..                            ...                            ...
67                         flores                        flowers
68             artes_e_artesanato          arts_and_craftmanship
69                fraldas_higiene            diapers_and_hygiene
70  fashion_roupa_infanto_juvenil      fashion_childrens_clothes
71             seguros_e_servicos          security_and_services

[72 rows x 2 columns]

In [72]:
product_name.drop(index = 0, inplace = True)

In [73]:
product_name

                 Product Category product category in english
1                    beleza_saude               health_beauty
2          informatica_acessorios       computers_accessories
3                      automotivo                        auto
4                 cama_mesa_banho              bed_bath_table
5                moveis_decoracao             furniture_decor
..                            ...                         ...
67                         flores                     flowers
68             artes_e_artesanato       arts_and_craftmanship
69                fraldas_higiene         diapers_and_hygiene
70  fashion_roupa_infanto_juvenil   fashion_childrens_clothes
71             seguros_e_servicos       security_and_services

[71 rows x 2 columns]

In [74]:
products['product_category_name'].nunique()

73

In [75]:
product_name['product category in english'].nunique()

71

In [76]:
# 71 categories common in both table 
# product a,b,c,d
# product_name a,b,e,f

In [77]:
# lets check the category presenf in products table but not in product_name
# iska mtlb product name ki category pura products table mein hai 
# pure 71 values are present in products table value 
product_name[~product_name['Product Category'].isin(products['product_category_name'])]

Empty DataFrame
Columns: [Product Category, product category in english]
Index: []

In [78]:
# yeh woh hai joh products table mein present hai par products_name table mein present nahi hai 
products[~products['product_category_name'].isin(product_name['Product Category'])]['product_category_name'].unique()

array([None, 'portateis_cozinha_e_preparadores_de_alimentos', 'pc_gamer'],
      dtype=object)

In [79]:
product_name.sort_values(by = ['Product Category'])['Product Category'].unique()

array(['agro_industria_e_comercio', 'alimentos', 'alimentos_bebidas',
       'artes', 'artes_e_artesanato', 'artigos_de_festas',
       'artigos_de_natal', 'audio', 'automotivo', 'bebes', 'bebidas',
       'beleza_saude', 'brinquedos', 'cama_mesa_banho', 'casa_conforto',
       'casa_conforto_2', 'casa_construcao', 'cds_dvds_musicais',
       'cine_foto', 'climatizacao', 'consoles_games',
       'construcao_ferramentas_construcao',
       'construcao_ferramentas_ferramentas',
       'construcao_ferramentas_iluminacao',
       'construcao_ferramentas_jardim',
       'construcao_ferramentas_seguranca', 'cool_stuff', 'dvds_blu_ray',
       'eletrodomesticos', 'eletrodomesticos_2', 'eletronicos',
       'eletroportateis', 'esporte_lazer', 'fashion_bolsas_e_acessorios',
       'fashion_calcados', 'fashion_esporte', 'fashion_roupa_feminina',
       'fashion_roupa_infanto_juvenil', 'fashion_roupa_masculina',
       'fashion_underwear_e_moda_praia', 'ferramentas_jardim', 'flores',
       'fraldas_higiene', 'industria_comercio_e_negocios',
       'informatica_acessorios', 'instrumentos_musicais', 'la_cuisine',
       'livros_importados', 'livros_interesse_geral', 'livros_tecnicos',
       'malas_acessorios', 'market_place', 'moveis_colchao_e_estofado',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'moveis_decoracao', 'moveis_escritorio', 'moveis_quarto',
       'moveis_sala', 'musica', 'papelaria', 'pcs', 'perfumaria',
       'pet_shop', 'portateis_casa_forno_e_cafe', 'relogios_presentes',
       'seguros_e_servicos', 'sinalizacao_e_seguranca',
       'tablets_impressao_imagem', 'telefonia', 'telefonia_fixa',
       'utilidades_domesticas'], dtype=object)

In [80]:
product_name[product_name['Product Category'] == "pcs"]

   Product Category product category in english
54              pcs                   computers

In [81]:
product_name[product_name['Product Category'] == "portateis_casa_forno_e_cafe"]

               Product Category            product category in english
64  portateis_casa_forno_e_cafe  small_appliances_home_oven_and_coffee

In [82]:
products = pd.merge(products, product_name , left_on = "product_category_name" , right_on = 'Product Category', how = 'left')

In [83]:
products

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
0,2a5fd02982127e736ae8f4d6d020fcc8,utilidades_domesticas,1.0,utilidades_domesticas,housewares
1,3dcb77af8b9587985d046b195e105475,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table
2,cec51758e9839eb5414b214934430da6,sinalizacao_e_seguranca,1.0,sinalizacao_e_seguranca,signaling_and_security
3,b3f3d2afe706552a90fd99f870e4ddf5,None,NaN,NaN,NaN
4,5afcae10f25795d55b858f6a2b95233b,brinquedos,1.0,brinquedos,toys
...,...,...,...,...,...
32946,325c397d5d1eebe97422d6bc1ed8709d,moveis_escritorio,3.0,moveis_escritorio,office_furniture
32947,5e53af05c040b01584b81b3549945faf,construcao_ferramentas_ferramentas,3.0,construcao_ferramentas_ferramentas,costruction_tools_tools
32948,87b489e8ad10cd2b4e631cc1af34ff00,moveis_decoracao,2.0,moveis_decoracao,furniture_decor
32949,c8a148c82c4a80df54e7ceea266f9fb5,construcao_ferramentas_construcao,3.0,construcao_ferramentas_construcao,construction_tools_construction
32950,c0603988d17e4588dfce0f7f01978557,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table

In [84]:
products[products['product_category_name'] == 'pc_gamer']

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
5400,6727051471a0fc4a0e7737b57bff2549,pc_gamer,3.0,NaN,NaN
14852,dbe520fb381ad695a7e1f2807d20c765,pc_gamer,6.0,NaN,NaN
32501,0105b5323d24fc655f73052694dbbb3a,pc_gamer,4.0,NaN,NaN

In [85]:
products.loc[products['product_category_name'] == 'pc_gamer',"product category in english"] = 'computers'
products.loc[products['product_category_name'] == 'portateis_casa_forno_e_cafe', 'product category in english'] = 'small_appliances_home_oven_and_coffee'

In [86]:
products

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
0,2a5fd02982127e736ae8f4d6d020fcc8,utilidades_domesticas,1.0,utilidades_domesticas,housewares
1,3dcb77af8b9587985d046b195e105475,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table
2,cec51758e9839eb5414b214934430da6,sinalizacao_e_seguranca,1.0,sinalizacao_e_seguranca,signaling_and_security
3,b3f3d2afe706552a90fd99f870e4ddf5,None,NaN,NaN,NaN
4,5afcae10f25795d55b858f6a2b95233b,brinquedos,1.0,brinquedos,toys
...,...,...,...,...,...
32946,325c397d5d1eebe97422d6bc1ed8709d,moveis_escritorio,3.0,moveis_escritorio,office_furniture
32947,5e53af05c040b01584b81b3549945faf,construcao_ferramentas_ferramentas,3.0,construcao_ferramentas_ferramentas,costruction_tools_tools
32948,87b489e8ad10cd2b4e631cc1af34ff00,moveis_decoracao,2.0,moveis_decoracao,furniture_decor
32949,c8a148c82c4a80df54e7ceea266f9fb5,construcao_ferramentas_construcao,3.0,construcao_ferramentas_construcao,construction_tools_construction
32950,c0603988d17e4588dfce0f7f01978557,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table

In [87]:
products[products['product_category_name'] == 'portateis_casa_forno_e_cafe']

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
285,ff92ca9bb0b3f4ec00a9b76c9f68cb3a,portateis_casa_forno_e_cafe,6.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
1585,27274145782d0048827cb28b7786323b,portateis_casa_forno_e_cafe,6.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
2379,32bad49615b7c5da42609b98df97482c,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
3370,58c91c9e1ddc24815b7c15ac4e8fee5e,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
3866,81e02af7d00fcf604270221efe1d1b95,portateis_casa_forno_e_cafe,3.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
4352,7b9e46278112502bca6d6649e849fdf0,portateis_casa_forno_e_cafe,2.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
8087,e47b2f2b628e82c961a82a68a4400339,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
9055,9806189f9cb679bcd5326b460c2b9073,portateis_casa_forno_e_cafe,4.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
10605,4608a449f45011c89095f36265e75ec3,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
10639,6341aca5b02d00d80b6f4dead6816435,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
11330,938e036a795cdacb18ed3c5a598f6cf0,portateis_casa_forno_e_cafe,5.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
11653,206ee9f28d05f04f891e3cef4b220dd1,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
12590,58cda2faccdf7f8620e45b6a863efd3f,portateis_casa_forno_e_cafe,4.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
12777,31240eaae01b43247d878f3e89996e35,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
14024,514171f9d45a3d93574fc587ef775579,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
15039,f49e985b4cb2d0543890d6dd00077663,portateis_casa_forno_e_cafe,8.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
15760,17ec1cf6dc8dc7557ca34f1d64a93dc7,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
16582,eee404f099d4035b0f3e4dc374669a31,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
20805,69029de1e1a2dc6e3fd6a063f3cad923,portateis_casa_forno_e_cafe,3.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
22256,0433830caca22b01a0f477d31307b043,portateis_casa_forno_e_cafe,7.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
23012,224037b21bfa8621e39c265513ee6594,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
24425,63682d69d8d74bacf75360f6efb31fcb,portateis_casa_forno_e_cafe,3.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
25563,7b2a6e3216a405943fc9e3acbff18cae,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
27108,dcbe94f9e03c6dc3c6ef089765ee5181,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
27434,e8721f5914c9d5f55e228402b21351ad,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
28120,dcd7f9e6e4d98a3142c0819c124bacfe,portateis_casa_forno_e_cafe,3.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
28751,e5c50ee10712a01bfed9854a00502f8e,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
30074,b92211a0503b5226b3cd3dd1c7fb3687,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
30425,a1e8d472af4a2704d41604cff9eeaaa5,portateis_casa_forno_e_cafe,2.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
30808,1dff983bf86722fbc11a0c1d0ec13624,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
31847,56e04ad5959e2c30a6754d9cc1f098f2,portateis_casa_forno_e_cafe,1.0,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee

In [88]:
products.drop(columns = ['Product Category','product category in english'],inplace = True )

In [89]:
products

,product_id,product_category_name,product_photos_qty
0,2a5fd02982127e736ae8f4d6d020fcc8,utilidades_domesticas,1.0
1,3dcb77af8b9587985d046b195e105475,cama_mesa_banho,1.0
2,cec51758e9839eb5414b214934430da6,sinalizacao_e_seguranca,1.0
3,b3f3d2afe706552a90fd99f870e4ddf5,None,NaN
4,5afcae10f25795d55b858f6a2b95233b,brinquedos,1.0
...,...,...,...
32946,325c397d5d1eebe97422d6bc1ed8709d,moveis_escritorio,3.0
32947,5e53af05c040b01584b81b3549945faf,construcao_ferramentas_ferramentas,3.0
32948,87b489e8ad10cd2b4e631cc1af34ff00,moveis_decoracao,2.0
32949,c8a148c82c4a80df54e7ceea266f9fb5,construcao_ferramentas_construcao,3.0
32950,c0603988d17e4588dfce0f7f01978557,cama_mesa_banho,1.0

In [90]:
query = "select * from olist_sellers_dataset;"
seller = pd.read_sql(query, conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\2281735286.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  seller = pd.read_sql(query, conn)

In [91]:
seller

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [92]:
seller['seller_city']=seller['seller_city'].str.title()

In [93]:
seller.duplicated().sum()

np.int64(0)

In [94]:
seller['seller_id'].duplicated().sum()

np.int64(0)

In [95]:
def keep_only_text(x):
    if pd.isna(x):
        return x 
    # remove everything except alphabets and spaces 
    return re.sub(r"[^A-Za-z\s]","",str(x)).strip()

In [96]:
seller['seller_city'] = seller['seller_city'].apply(keep_only_text)

### Olist orders dataset

In [97]:
query = "select * from olist_orders_dataset"
orders = pd.read_sql(query,conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\189253224.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql(query,conn)

In [98]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [99]:
df = orders.copy()

In [100]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [101]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [102]:
## order approve date should be greater than order purchase timestamp 
## order estimated delivery date can be less or greater than order_deleiverd customer date 

# keep only those rows whoes 
## order_approve_date < order_delivered_date 
## order_approve_date > order_purchase_timestamp

In [103]:
orders[(orders['order_approved_at'] - orders['order_purchase_timestamp']).dt.total_seconds() / 86400 >= 0]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [104]:
orders=orders[
    ((orders['order_approved_at'] - orders['order_purchase_timestamp']).dt.total_seconds() / 86400 >= 0) &
    ((orders['order_delivered_carrier_date'] - orders['order_approved_at']).dt.days >= 0) 
    
]

In [105]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [106]:
orders['order_status'].unique()

array(['delivered', 'shipped', 'canceled'], dtype=object)

In [107]:
to_remove = orders[(orders["order_status"] == "canceled") & (orders["order_delivered_customer_date"].notnull())].index

In [108]:
to_remove

Index([2921, 8791, 58266, 59332, 92636, 94399], dtype='int64')

In [109]:
orders.drop(to_remove,inplace= True)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\2038769633.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders.drop(to_remove,inplace= True)

In [110]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [111]:
orders[(orders["order_status"] == "canceled") & (~orders["order_delivered_customer_date"].isnull())]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [112]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [113]:
orders.duplicated().sum()

np.int64(0)

In [114]:
orders['order_status'].unique()

array(['delivered', 'shipped', 'canceled'], dtype=object)

### olist_orders_payments_dataset

In [115]:
query = "select * from olist_order_payments_dataset"
payments = pd.read_sql(query , conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\1210073234.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  payments = pd.read_sql(query , conn)

In [116]:
payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,baa5545eb30192ce3b92bcf1b8e19437,1,boleto,1,64.510002
1,da726e4e14776093627536acd474872c,1,credit_card,7,147.149994
2,12f12b0c970ed338e7a4cf857fd1eb33,1,boleto,1,27.770000
3,58654344ef4d9b4aefb2ee36618d9751,1,boleto,1,148.320007
4,d69c7c969d600368c5f533b188e402eb,1,boleto,1,30.709999
...,...,...,...,...,...
103881,77ae1cf0361cb41c1637cc79e170c9c1,1,credit_card,1,99.220001
103882,87df71eb46077c66a8e53d4e92bc71ef,1,boleto,1,98.699997
103883,3dafc0bec8f7cc53ecc6671ca9c646d7,1,credit_card,1,29.910000
103884,c470c4940c653080f16ba7e4cf1eb08c,1,credit_card,1,35.689999
103885,9aa048e5cf0be9f697cc0fe8d1e0d6db,1,credit_card,4,100.779999

In [117]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [118]:
payments.sort_values(by = 'payment_sequential', ascending = False)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
45345,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.260000
45348,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.049999
11122,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.019997
38630,ccf804e764ed5650cd8759557269dc13,26,voucher,1,23.100000
85824,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.270000
...,...,...,...,...,...
35343,a9a682eb2347718eaae4a75d99f205d2,1,boleto,1,69.900002
35342,7a1616110b24cfd12bdec238b385ec42,1,boleto,1,58.000000
35341,7bf074a71da84423b09ada4ec2932bf1,1,credit_card,2,24.709999
35340,d8efc4afe919de73af09d4319b503f08,1,credit_card,8,206.910004
103885,9aa048e5cf0be9f697cc0fe8d1e0d6db,1,credit_card,4,100.779999

In [119]:
payments[payments['order_id'] == 'fa65dad1b0e818e3ccc5cb0e39231352' ].sort_values(by = 'payment_sequential')

,order_id,payment_sequential,payment_type,payment_installments,payment_value
20558,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.710000
29311,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.510000
71878,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.950000
16222,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.160000
34567,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.660000
35885,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.020000
88830,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.320000
75090,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.020000
23511,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.080000
25802,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.860000
38756,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.030000
79774,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.600000
84122,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.000000
43059,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.000000
69606,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.040000
84287,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.860000
85907,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.720000
86558,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.730000
80958,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.020000
99574,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.000000
80476,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.110000
2957,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.030000
91403,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.860001
1564,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.420000
31116,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.680000
85824,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.270000
11122,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.019997
45348,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.049999
45345,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.260000

In [120]:
payments['payment_installments'].unique()

array([ 1,  7,  2, 10,  8,  3,  4,  6,  5,  9, 17, 15, 12, 14, 13, 24, 11,
       16, 18, 20, 21, 22,  0, 23])

In [121]:
payments.drop(columns = ['payment_sequential','payment_installments'],inplace = True)

In [122]:
payments=payments.groupby(['order_id','payment_type'])['payment_value'].sum().reset_index()

In [123]:
payments

                                order_id payment_type  payment_value
0       00010242fe8c5a6d1ba2dd792cb16214  credit_card      72.190002
1       00018f77f2f0320c557190d7a144bdd3  credit_card     259.829987
2       000229ec398224ef6ca0657da4fc703e  credit_card     216.869995
3       00024acbcdf0a6daa1e931b038114c75  credit_card      25.780001
4       00042b26cf59d7ce69dfabb4e55b4fd9  credit_card     218.039993
...                                  ...          ...            ...
101681  fffc94f6ce00a00581880bf54a75a037       boleto     343.399994
101682  fffcd46ef2263f404302a634eb57f7eb       boleto     386.529999
101683  fffce4705a9662cd70adb13d4a31832d  credit_card     116.849998
101684  fffe18544ffabc95dfada21779c9644f  credit_card      64.709999
101685  fffe41c64501cc87c801fd61db3f6244  credit_card      55.790001

[101686 rows x 3 columns]

In [124]:
payments[payments['order_id'] == 'fa65dad1b0e818e3ccc5cb0e39231352' ]

                               order_id payment_type  payment_value
99453  fa65dad1b0e818e3ccc5cb0e39231352      voucher     457.989998

In [125]:
payments.shape

(101686, 3)

In [126]:
payments.head()

                           order_id payment_type  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214  credit_card      72.190002
1  00018f77f2f0320c557190d7a144bdd3  credit_card     259.829987
2  000229ec398224ef6ca0657da4fc703e  credit_card     216.869995
3  00024acbcdf0a6daa1e931b038114c75  credit_card      25.780001
4  00042b26cf59d7ce69dfabb4e55b4fd9  credit_card     218.039993

In [127]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [128]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [129]:
print(orders['order_id'].nunique())
print(payments['order_id'].nunique())

96279
99440

In [130]:
99440-96279

3161

In [131]:
## orders cancelled orders  unki payments id mere payment table mein padi ho 
## ordres table mein joh rows clean kari unn clean kari hui rows ki order_id payment id mein padi ho payemnt table mein 
## orders    payment 
## payment   orders

In [132]:
len(orders[orders['order_status'] == 'canceled']) # isse hume yeh pata chalta hia ki pehal reson galat hai

69

In [133]:
orders[~orders['order_id'].isin(payments['order_id'])]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04

In [134]:
payments[~payments['order_id'].isin(orders['order_id'])].nunique() ## 2nd reason may be the case, the reason of using nunique kyu ki
#payments voucher , credit card wale se bhi kiya ho aur repeat kar raha ho so its better to use nunique

order_id         3162
payment_type        5
payment_value    2762
dtype: int64

In [135]:
# orders --- cleaned
# df ---- uncleaned

In [136]:
# df --- 1000
# orders = 890
# cleaned - 110 order id

In [137]:
df[~df['order_id'].isin(orders['order_id'])].nunique()  ## this confirms 2nd reason

order_id                         3162
customer_id                      3162
order_status                        8
order_purchase_timestamp         3159
order_approved_at                2798
order_delivered_carrier_date     1189
order_delivered_customer_date    1370
order_estimated_delivery_date     421
dtype: int64

In [138]:
# jab meine df table ko clean karke orders table banaya toh 3162 hatt gaye

In [139]:
orders = pd.merge(orders,payments, on = 'order_id', how = 'inner')

In [140]:
orders['order_id'].nunique()

96278

In [141]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.460007
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.119995
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.199997
...,...,...,...,...,...,...,...,...,...,...
98444,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,credit_card,85.080002
98445,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.000000
98446,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.010010
98447,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004
98448,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.860001

In [142]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.460007
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.119995
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.199997
...,...,...,...,...,...,...,...,...,...,...
98444,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,credit_card,85.080002
98445,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.000000
98446,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.010010
98447,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004
98448,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.860001

### olist items dataset

In [143]:
query = "select * from olist_order_items_dataset"
olist_items = pd.read_sql(query, conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\1154614543.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  olist_items = pd.read_sql(query, conn)

In [144]:
olist_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.990000,12.790000
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.899994,18.139999
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.989990,43.410000
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.000000,36.529999
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.900002,16.950001
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.990002,8.720000
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.000000,12.790000

In [145]:
print(orders['order_id'].nunique())
print(olist_items['order_id'].nunique())

96278
98666

In [146]:
# merge --- inner join 
orders = pd.merge(orders, olist_items , on = 'order_id' , how = 'inner' )

In [147]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.460007,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.699997,22.760000
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.119995,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.899994,19.219999
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.199997,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.000000,27.200001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.000000,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.899994,20.100000
112306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.010010,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.990005,65.019997
112307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.860001,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.500000,18.360001

In [148]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112310 entries, 0 to 112309
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112310 non-null  object
 1   customer_id                    112310 non-null  object
 2   order_status                   112310 non-null  object
 3   order_purchase_timestamp       112310 non-null  datetime64[ns]
 4   order_approved_at              112310 non-null  datetime64[ns]
 5   order_delivered_carrier_date   112310 non-null  datetime64[ns]
 6   order_delivered_customer_date  111039 non-null  datetime64[ns]
 7   order_estimated_delivery_date  112310 non-null  datetime64[ns]
 8   payment_type                   112310 non-null  object
 9   payment_value                  112310 non-null  float64
 10  order_item_id                  112310 non-null  int64
 11  product_id                     112310 non-null  object
 12  seller_id                      112310 non-null  object
 13  shipping_limit_date            112310 non-null  datetime64[ns]
 14  price                          112310 non-null  float64
 15  freight_value                  112310 non-null  float64
dtypes: datetime64[ns](6), float64(3), int64(1), object(6)
memory usage: 13.7+ MB

In [149]:
orders = orders[(orders['shipping_limit_date'] > orders['order_purchase_timestamp']) & 
(orders['shipping_limit_date']  > orders['order_approved_at']) &
(orders['shipping_limit_date'] < orders['order_delivered_customer_date'])]

In [150]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.460007,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.699997,22.760000
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.119995,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.899994,19.219999
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.199997,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.000000,27.200001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.000000,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.899994,20.100000
112306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.010010,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.990005,65.019997
112307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.860001,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.500000,18.360001

In [151]:
orders['order_item_id'].value_counts()

order_item_id
1     77334
2      7485
3      1747
4       727
5       335
6       192
7        45
8        30
9        23
10       21
11       15
12       12
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [152]:
orders.sort_values(by = ['order_item_id','order_id'],ascending = False)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
100242,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,21,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.800000,6.570000
106170,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,20,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.440000
100241,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,20,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.200000,7.890000
98128,1b15974a0141d54e36626dca3fdc731a,be1b70680b9f9694d8c70f41fa3dc92b,delivered,2018-02-22 15:30:41,2018-02-24 03:20:27,2018-03-02 00:18:01,2018-03-05 15:22:27,2018-03-08,boleto,2202.399902,20,ee3d532c8a438679776d222e997606b3,8e6d7754bc7e0f22c96d255ebda59eba,2018-03-01 02:50:48,100.000000,10.120000
106169,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,19,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,98.699997,14.440000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111297,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,delivered,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,credit_card,31.750000,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.900000,11.850000
5863,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,credit_card,218.039993,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.899994,18.139999
7056,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,credit_card,216.869995,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001
81124,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,credit_card,259.829987,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000
96209,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,credit_card,72.190002,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000

In [153]:
orders[orders['customer_id'] == 'fc3d1daec319d62d49bfb5e1f83123e9']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
100222,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,1,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100223,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,2,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100224,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,3,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100225,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,4,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100226,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,5,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100227,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,6,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100228,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,7,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100229,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,8,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100230,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,9,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100231,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,10,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100232,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,11,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100233,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,12,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100234,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,13,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100235,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,14,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100236,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,15,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100237,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,16,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100238,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,17,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100239,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,18,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100240,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,19,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100241,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,20,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.2,7.89
100242,8272b63d03f5f79c56e9e4120aec44ef,fc3d1daec319d62d49bfb5e1f83123e9,delivered,2017-07-16 18:19:25,2017-07-17 18:25:23,2017-07-20 15:45:53,2017-07-31 18:03:02,2017-07-28,credit_card,196.110001,21,79ce45dbc2ea29b22b5a261bbb7b7ee7,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,7.8,6.57

In [154]:
orders[orders['order_id'] == 'e481f51cbdc54678b7cc49136f2d6af7']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72

In [155]:
orders.drop(columns = ['order_item_id'],inplace = True)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\948205616.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders.drop(columns = ['order_item_id'],inplace = True)

In [156]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.990000,8.720000
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,boleto,141.460007,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.699997,22.760000
3,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,credit_card,179.119995,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.899994,19.219999
4,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,credit_card,72.199997,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.000000,27.200001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,credit_card,195.000000,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.899994,20.100000
112306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,credit_card,271.010010,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.990005,65.019997
112307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,credit_card,441.160004,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.990005,40.590000
112309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,debit_card,86.860001,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.500000,18.360001

In [157]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [158]:
orders = orders.groupby(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date']).agg(price = ("price",'sum'),freight_value = ('freight_value','sum'),Quantity = ("product_id","count")).reset_index()

In [159]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,credit_card,72.190002,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000,1
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,credit_card,259.829987,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000,1
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,credit_card,216.869995,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001,1
3,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,credit_card,218.039993,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.899994,18.139999,1
4,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,delivered,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,credit_card,31.750000,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.900000,11.850000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80151,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,boleto,356.760010,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,220.000000,136.759995,4
80152,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,delivered,2018-06-19 09:27:48,2018-06-19 09:58:03,2018-06-29 13:46:00,2018-07-05 17:51:08,2018-07-23,credit_card,139.880005,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.849998,20.030001,1
80153,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,boleto,343.399994,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.989990,43.410000,1
80154,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,boleto,386.529999,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.000000,36.529999,1
80155,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,credit_card,55.790001,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.000000,12.790000,1

In [160]:
orders['Quantity'].value_counts()

Quantity
1     74717
2      4142
3       728
4       299
6       130
5       118
10        5
7         3
8         2
20        2
12        2
15        2
14        2
9         2
13        1
11        1
Name: count, dtype: int64

In [161]:
orders[orders['order_id'] == 'e481f51cbdc54678b7cc49136f2d6af7']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
71818,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,credit_card,18.120001,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1
71819,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,voucher,20.590000,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1

In [162]:
orders[orders['order_id'] == 'ab14fdcfbe524636d65ee38360e22ce8']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
53512,ab14fdcfbe524636d65ee38360e22ce8,bd5d39761aa56689a265d95d8d32b8be,delivered,2017-08-23 09:22:34,2017-08-24 14:30:23,2017-08-25 20:07:36,2017-09-02 12:13:03,2017-09-21,credit_card,2262.800049,9571759451b1d780ee7c15012ea109d4,ce27a3cc3c8cc1ea79d11e561e9bebb6,2017-08-30 14:30:23,1973.999939,288.799992,20

In [163]:
orders.shape

(80156, 16)

In [164]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_value,product_id,seller_id,shipping_limit_date,price,freight_value,Quantity
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,credit_card,72.190002,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.290000,1
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,credit_card,259.829987,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.930000,1
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,credit_card,216.869995,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.000000,17.870001,1
3,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,credit_card,218.039993,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.899994,18.139999,1
4,00054e8431b9d7675808bcb819fb4a32,32e2e6ab09e778d99bf2e0ecd4898718,delivered,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,credit_card,31.750000,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.900000,11.850000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80151,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27,boleto,356.760010,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,220.000000,136.759995,4
80152,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,delivered,2018-06-19 09:27:48,2018-06-19 09:58:03,2018-06-29 13:46:00,2018-07-05 17:51:08,2018-07-23,credit_card,139.880005,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.849998,20.030001,1
80153,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,boleto,343.399994,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.989990,43.410000,1
80154,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,boleto,386.529999,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.000000,36.529999,1
80155,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,credit_card,55.790001,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.000000,12.790000,1

In [165]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,Osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,Itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,Nova Venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,Mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,Sao Paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,Parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,Rio De Janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,Taboao Da Serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,Alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,Osasco,SP

In [166]:
pd.merge(orders,customers, left_on = 'customer_id', right_on = 'customer_unique_id', how = 'inner') # iise yeh pata chal ki customer_unique_id

Empty DataFrame
Columns: [order_id, customer_id_x, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, payment_type, payment_value, product_id, seller_id, shipping_limit_date, price, freight_value, Quantity, customer_id_y, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []

[0 rows x 21 columns]

In [167]:
customers.drop(columns = 'customer_unique_id',inplace = True)

In [169]:
 customers

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,6273,Osasco,SP
1,000161a058600d5901f007fab4c27140,35550,Itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,29830,Nova Venecia,ES
3,0002414f95344307404f0ace7a26f1d5,39664,Mendonca,MG
4,000379cdec625522490c315e70c7a9fb,4841,Sao Paulo,SP
...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,95630,Parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,22461,Rio De Janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,6754,Taboao Da Serra,SP
99439,ffffa3172527f765de70084a7e53aae8,37130,Alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,6172,Osasco,SP

In [178]:
query = "select * from olist_order_reviews_dataset"
reviews = pd.read_sql(query, conn)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\767382561.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  reviews = pd.read_sql(query, conn)

In [179]:
reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,None,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,None,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,None,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,None,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,None,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,None,None,2018-07-07,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,None,None,2017-12-09,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,None,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,None,None,2018-07-01,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,None,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03 21:01:49

In [180]:
reviews = reviews[reviews["order_id"].isin(orders["order_id"])]

In [181]:
reviews.drop(columns="review_comment_title", inplace=True)

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\512982446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews.drop(columns="review_comment_title", inplace=True)

In [182]:
reviews['review_answer_timestamp'] = reviews['review_answer_timestamp'].dt.date

C:\Users\welcome\AppData\Local\Temp\ipykernel_17852\3752694327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews['review_answer_timestamp'] = reviews['review_answer_timestamp'].dt.date

In [183]:
reviews

,review_id,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,2018-03-10,2018-03-11
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,2018-02-17,2018-02-18
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02
7,7c6400515c67679fbee952a7525281ef,c31a859e34e3adac22f376954e19b39d,5,None,2018-08-14,2018-08-14
...,...,...,...,...,...,...
99216,115d72425fc59eec9a2e9d7594c6d93d,acd45245723df7cb52772a34416b41b1,3,None,2018-05-08,2018-05-10
99217,c6b270c61f67c9f7cb07d84ea8aeaf8b,48f7ee67313eda32bfcf5b9c1dd9522d,5,None,2017-12-13,2017-12-14
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,None,2018-07-07,2018-07-14
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,None,2017-12-09,2017-12-11
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,None,2018-07-01,2018-07-02

In [171]:
customers.to_csv('cleaned_customers.csv')

In [172]:
geo.to_csv('cleaned_geo.csv')

In [173]:
products.to_csv('cleaned_products.csv')

In [174]:
seller.to_csv('cleaned_seller.csv')

In [175]:
orders.to_csv('cleaned_orders.csv')

In [176]:
payments.to_csv('cleaned_payments.csv')

In [177]:
olist_items.to_csv('cleaned_olist_items.csv')

In [184]:
reviews.to_csv('cleaned_reviews.csv')